
// Code generated by go generate; DO NOT EDIT.
// using data from templates/templates
package templates

func TemplatesMap() map[string]string {
    templatesMap := make(map[string]string)

templatesMap["go.cmd.tmpl"] = `// Code generated by cli-generator; DO NOT EDIT.
package cmd

{{ $name := strings.CamelCase .cmd.name }}

import (
	{{ if .cmd.root }}
	"fmt"
	"github.com/spf13/viper"
	{{ end }}
	{{- if not .cmd.root }}
	handler "{{ .go.package }}/pkg/{{$name}}"
	{{end}}
	"github.com/spf13/cobra"
	
)

{{- if .cmd.root }}
var cnf *viper.Viper = viper.New()
{{- end }}

var {{$name}}CmdOptions struct {
	{{ range .cmd.flags }}
	{{- .name | strings.CamelCase }} {{ .type | toGolangType }}
	{{ end }}
}

var {{$name}}Cmd = &cobra.Command{
	{{- if .cmd.root }}
	Use:     "{{ .spec.metadata.name }}",
	Version: "{{ .spec.metadata.version }}",
	{{ else }}
	Use:     "{{ .cmd.name }}",
	RunE: func(cmd *cobra.Command, args []string) error {
		h := &handler.Handler{}
		return h.Handle(cnf)
	},
	{{- end }}
	{{- if .spec.metadata.description }}
	Long: "{{ .spec.metadata.description }}",
	{{- end }}
	PreRun: func(cmd *cobra.Command, args []string) {
		{{- if not .cmd.root }}
		{{ .cmd.parent }}Cmd.PreRun(cmd, args)
		{{- end }}
		{{ range .cmd.flags }}
		cnf.Set("{{- .name | strings.CamelCase }}", {{$name}}CmdOptions.{{- .name | strings.CamelCase }})
		{{ end }}
	},
}


{{ if .cmd.root }}
// Execute - execute the root command
func Execute() {
	err := {{$name}}Cmd.Execute()
	if err != nil {
		fmt.Println(err.Error())
	}
}
{{ end }}

func init() {
{{- range .cmd.flags }}
	{{- if .envVar }}
	cnf.BindEnv("{{ .name }}", "{{ .envVar }}")
	{{- end }}
	{{- if ( has . "default" ) }}
	cnf.SetDefault("{{ strings.CamelCase .name}}", {{ .default }})
	{{- end }}

	{{ $name }}Cmd.PersistentFlags().{{ .type | golangFlagFunc }}(&{{ $name }}CmdOptions.{{- .name | strings.CamelCase }}, "{{- .name }}", cnf.{{ golangFlagDefaultFunc .type }}("{{ strings.CamelCase .name}}"), "{{ default "" .description }}")
	
{{- end }}

{{- if .cmd.parent }}
	{{ .cmd.parent }}Cmd.AddCommand({{$name}}Cmd)
{{- end }}
}` 

templatesMap["go.handler.tmpl"] = `package {{ strings.CamelCase .cmd.name }}

import (
	"fmt"
	"github.com/spf13/viper"
)

type (
	// Handler - exposed struct that implementd Handler interface
	Handler struct{}
)

// Handle - the function that will be called from the CLI with viper config
// to provide access to all flags
func (g *Handler) Handle(cnf *viper.Viper) error {
	fmt.Printf("Handler for command: {{ .cmd.name }}\n")
	{{ range .cmd.flags }}
	{{ if eq .type "arrayString" }}
	data := cnf.{{ .type | golangFlagDefaultFunc }}("{{.name}}")
	for index, d := range data {
		fmt.Printf("flag name: {{ .name }}_%d, value: %s\n", index, d)
	}
	{{ else }}
	fmt.Printf("flag name: {{ .name }}, value: %s\n", cnf.{{ .type | golangFlagDefaultFunc }}("{{.name}}"))
	{{ end }}
	{{ end }}
	return nil
}` 

templatesMap["go.main.tmpl"] = `// Code generated by cli-generator; DO NOT EDIT.
package main

import (
	cmd "{{ .go.package }}/cmd"
)

func main() {
	cmd.Execute()
}` 

templatesMap["go.makefile.tmpl"] = `outfile = /usr/local/bin/{{.spec.metadata.name}}
build:
	@echo "Building go binary"
	@go build -o $(outfile) *.go
	@chmod +x $(outfile)
` 

    return  templatesMap
}
