
// Code generated by cli-generator; DO NOT EDIT.
package cmd



import (
	
	handler "github.com/olegsu/cli-generator/pkg/generate"
	
	"github.com/spf13/cobra"
	
)

var generateCmdOptions struct {
	language string
	goPackage string
	spec string
	projectDir string
	createHandlers bool
	calculateSha bool
	
}

var generateCmd = &cobra.Command{
	Use:     "generate",
	RunE: func(cmd *cobra.Command, args []string) error {
		h := &handler.Handler{}
		return h.Handle(cnf)
	},
	Long: "Generate CLI entrypoints from spec file",
	PreRun: func(cmd *cobra.Command, args []string) {
		
		cnf.Set("language", generateCmdOptions.language)
		
		cnf.Set("goPackage", generateCmdOptions.goPackage)
		
		cnf.Set("spec", generateCmdOptions.spec)
		
		cnf.Set("projectDir", generateCmdOptions.projectDir)
		
		cnf.Set("createHandlers", generateCmdOptions.createHandlers)
		
		cnf.Set("calculateSha", generateCmdOptions.calculateSha)
		
	},
}




func init() {

	generateCmd.Flags().StringVar(&generateCmdOptions.language, "language", cnf.GetString("language"), "")

	generateCmd.Flags().StringVar(&generateCmdOptions.goPackage, "go-package", cnf.GetString("goPackage"), "")

	generateCmd.Flags().StringVar(&generateCmdOptions.spec, "spec", cnf.GetString("spec"), "")

	generateCmd.Flags().StringVar(&generateCmdOptions.projectDir, "project-dir", cnf.GetString("projectDir"), "")

	generateCmd.Flags().BoolVar(&generateCmdOptions.createHandlers, "create-handlers", cnf.GetBool("createHandlers"), "")

	generateCmd.Flags().BoolVar(&generateCmdOptions.calculateSha, "calculate-sha", cnf.GetBool("calculateSha"), "")
	rootCmd.AddCommand(generateCmd)
}