// Code generated by cli-generator; DO NOT EDIT.
package cmd



import (
	
	handler "github.com/olegsu/cli-generator/pkg/validate"
	
	"github.com/spf13/cobra"
	
)

var validateCmdOptions struct {
	spec string
	
}

var validateCmd = &cobra.Command{
	Use:     "validate",
	RunE: func(cmd *cobra.Command, args []string) error {
		h := &handler.Handler{}
		return h.Handle(cnf)
	},
	Long: "Generate CLI entrypoints from spec file",
	PreRun: func(cmd *cobra.Command, args []string) {
		rootCmd.PreRun(cmd, args)
		
		cnf.Set("spec", validateCmdOptions.spec)
		
	},
}




func init() {

	validateCmd.PersistentFlags().StringVar(&validateCmdOptions.spec, "spec", cnf.GetString("spec"), "")
	rootCmd.AddCommand(validateCmd)
}